---
- name : Install node and npm
  hosts: 209.38.218.181
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm


- name: Create new linux user for nodejs app
  hosts: 209.38.218.181
  tasks:
    - name: Create linux user
      user:
        name: nodejs
        comment: Node user
        group: admin


- name: Deploy nodejs app
  hosts: 209.38.218.181
  become: True
  become_user: nodejs
  tasks:
    - name: Unpack the nodejs file
      unarchive:
        src: /home/hyf/ansible/nodejs-app/nodejs-app-1.0.0.tgz
        dest: /home/nodejs
    - name: Install dependencies
      npm:
        path: /home/nodejs/package
    - name: Start the application
      command:
        chdir: /home/nodejs/package/app
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}